name: Deploy Node App to Github Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main # or "master" or any branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Test the project
      - name: Run Tests
        run: npm test

      # Build the project
      - name: Build project
        run: npm run build

      # Deploy to github pages
      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub automatically provides this secret
          publish_dir: ./dist # The directory where your build files are located (e.g., "dist", "build")
