name: Deploy Node App

on:
  push:
    branches:
      - main # or "master" or any branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Deploy (Example using rsync)
        run: echo "Deploy script here (e.g., rsync, ssh, vercel CLI)"
